{
 "title": "Scimbridge deployment - Prod",
 "description": "Scimbridge deployment monitoring Prod",
 "tags": [
  "1Password",
  "Infrastructure"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "platform-secrets-manag-yjeap" },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success{namespace=\"$namespace\"}, instance)"
    }
   },
   { "name": "helm_release_name", "query": "op-scim-bridge-prod" },
   { "name": "helm_chart_name", "query": "op-scim-bridge" },
   {
    "name": "bridge_pod_name_regex",
    "query": "op-scim-bridge-prod-[0-9a-zA-Z]*-[0-9a-zA-Z]*$"
   },
   {
    "name": "redis_pod_name_regex",
    "query": "op-scim-bridge-prod-redis-master-[0-9a-zA-Z]*-[0-9a-zA-Z]*$"
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Latest available Chart version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helm_chart_info{cluster=\"$cluster\",namespace=\"$namespace\", chart=\"$helm_chart_name\", release=\"$helm_release_name\"}",
     "legendFormat": "{{latestVersion}}"
    }
   ]
  },
  {
   "title": "Running instances",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\",namespace=\"$namespace\", workload_type=\"deployment\"}) by (workload, workload_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scimbridge deployment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum (kube_deployment_status_replicas_available{cluster=\"$cluster\",namespace=\"$namespace\", deployment=\"$helm_release_name\"}) without (instance, pod, job, endpoint, service, container)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Currently used Chart version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helm_chart_info{cluster=\"$cluster\",namespace=\"$namespace\", chart=\"$helm_chart_name\", release=\"$helm_release_name\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Scimbridge redis deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum (kube_deployment_status_replicas_available{cluster=\"$cluster\",namespace=\"$namespace\", deployment=\"$helm_release_name-redis-master\"}) without (instance, pod, job, endpoint, service, container)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Current \"appVersion\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helm_chart_info{cluster=\"$cluster\",namespace=\"$namespace\", chart=\"$helm_chart_name\", release=\"$helm_release_name\"}",
     "legendFormat": "{{appVersion}}"
    }
   ]
  },
  {
   "title": "Chart Last updated (UTC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helm_chart_timestamp{cluster=\"$cluster\",namespace=\"$namespace\", chart=\"$helm_chart_name\", release=\"$helm_release_name\"}",
     "legendFormat": "{{updated}}"
    }
   ]
  },
  {
   "title": "Bridge (CPU)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\", container!=\"POD\",pod!=\"\", container!=\"\"}[$__rate_interval])) / max(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=\"$namespace\", job=\"kube-state-metrics\", pod=~\"$bridge_pod_name_regex\",resource=\"cpu\",unit=\"core\",container!=\"POD\",pod!=\"\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridge (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\", container!=\"POD\"}[$__rate_interval])) * 1000",
     "legendFormat": "Usage (milli cores)"
    },
    {
     "expr": "cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$bridge_pod_name_regex\",resource=\"cpu\",unit=\"core\",container!=\"POD\",pod!=\"\", container!=\"\"} * 1000",
     "legendFormat": "Request (milli cores)"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\"}[$__rate_interval])) * 1000",
     "legendFormat": "Throttled (milli cores)"
    }
   ]
  },
  {
   "title": "Bridge (Memory)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\",metrics_path=~\"/metrics/cadvisor\"}) / max(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\", resource=\"memory\", unit=\"byte\", job=\"kube-state-metrics\",container!=\"POD\",pod!=\"\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridge (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\",container!=\"POD\",container!=\"\",metrics_path=~\"/metrics/cadvisor\"}) / max(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$bridge_pod_name_regex\", resource=\"memory\", unit=\"byte\", job=\"kube-state-metrics\", container!=\"POD\",pod!=\"\", container!=\"\"})",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Redis (CPU)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$redis_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\"}[$__rate_interval])) / max(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=\"$namespace\", job=\"kube-state-metrics\", pod=~\"$redis_pod_name_regex\",resource=\"cpu\",unit=\"core\",container!=\"POD\",pod!=\"\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$redis_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\"}[$__rate_interval])) * 1000",
     "legendFormat": "Usage (milli cores)"
    },
    {
     "expr": "cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$redis_pod_name_regex\",resource=\"cpu\",unit=\"core\",container!=\"POD\",pod!=\"\", container!=\"\"} * 1000",
     "legendFormat": "Request (milli cores)"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", container=\"$redis_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\"}[$__rate_interval])) * 1000",
     "legendFormat": "Throttled (milli cores)"
    }
   ]
  },
  {
   "title": "Redis (Memory)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$redis_pod_name_regex\",container!=\"POD\",pod!=\"\", container!=\"\",metrics_path=~\"/metrics/cadvisor\"}) / max(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$redis_pod_name_regex\", resource=\"memory\", unit=\"byte\", job=\"kube-state-metrics\",container!=\"POD\",pod!=\"\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$helm_release_name-redis-master-.*\", container!=\"POD\",pod!=\"\", container!=\"\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$helm_release_name-redis-master-.*\",container!=\"POD\",pod!=\"\", container!=\"\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"op-scim-bride-redis-master-.*\",container!=\"POD\",pod!=\"\", container!=\"\",metrics_path=~\"/metrics/cadvisor\"}) / max(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=\"$namespace\", job=\"kube-state-metrics\", pod=~\"op-scim-bride-redis-master-.*\", resource=\"memory\", unit=\"byte\",container!=\"POD\",pod!=\"\", container!=\"\"})",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Probe status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "probe_success{cluster=\"$cluster\",instance=~\"$target\"}",
     "legendFormat": "{{  instance }}"
    }
   ]
  },
  {
   "title": "SSL expiry overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=\"$cluster\",namespace=\"$namespace\"} - time()",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=\"$cluster\",instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{cluster=\"$cluster\",instance=~\"$target\"})"
    }
   ]
  }
 ]
}