{
 "title": "Cloud Engineering Adoption",
 "tags": [ "Adoption" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasources", "query": "prometheus" },
   {
    "name": "capNS",
    "label": "Capability Namespaces",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster=\"$cluster\",namespace!=\"\"},namespace)"
    }
   },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Capability Kubernetes resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_namespace_labels{namespace!=\"\",cluster=\"$cluster\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "count(kube_deployment_labels{namespace=~\"$capNS\",cluster=\"$cluster\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "count(kube_service_labels{namespace=~\"$capNS\",cluster=\"$cluster\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "count(kube_ingress_labels{namespace=~\"$capNS\",cluster=\"$cluster\"})",
     "legendFormat": "Ingresses"
    }
   ]
  },
  {
   "title": "Capability namespaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_namespace_labels{label_capability_name!=\"\",cluster=\"$cluster\"})",
     "legendFormat": "Capability namespaces"
    },
    {
     "expr": "count(kube_namespace_labels{cluster=\"$cluster\"})",
     "legendFormat": "Total namespaces"
    },
    {
     "expr": "count(kube_namespace_labels{label_legacy=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "Legacy capabilities"
    }
   ]
  },
  {
   "title": "Capability pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_labels{namespace=~\"$capNS\",cluster=\"$cluster\"})",
     "legendFormat": "Capability pods"
    },
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"})",
     "legendFormat": "Total pods"
    },
    {
     "expr": "count(kube_pod_labels{namespace=~\"$capNS\",cluster=\"$cluster\"}) / count(kube_namespace_labels{label_capability_name!=\"\",cluster=\"$cluster\"})",
     "legendFormat": "Avg. pods per capability"
    }
   ]
  },
  {
   "title": "Grafana adoption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_service_labels{service=\"grafana\",namespace!=\"monitoring\",cluster=\"$cluster\"})",
     "legendFormat": "Grafana instances"
    },
    {
     "expr": "count(kube_namespace_labels{namespace!=\"kube-system\", namespace!=\"default\", namespace!=\"kube-public\",namespace!=\"fluentd\",namespace!=\"flux-system\",namespace!=\"kube-node-lease\",namespace!=\"monitoring\",namespace!=\"podinfo\",namespace!=\"selfservice\",namespace!=\"traefik\",namespace!=\"velero\",namespace!=\"atlantis\",cluster=\"$cluster\"})",
     "legendFormat": "Capability namespaces"
    }
   ]
  },
  {
   "title": "Traefik Entrypoint Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=\"web\",cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Request rate"
    }
   ]
  },
  {
   "title": "Unauthorised Use of Reserved Priority Classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{priority_class=~\"system.*\",cluster=\"$cluster\",namespace!~\"kube-system|monitoring|flux-system|nvidia-device-plugin\"}) OR on() vector(0)",
     "legendFormat": "system*"
    },
    {
     "expr": "count(kube_pod_info{priority_class=~\"service-critical\",cluster=\"$cluster\",namespace!~\"kube-system|velero\"}) OR on() vector(0)",
     "legendFormat": "service-critical"
    },
    {
     "expr": "count(kube_pod_info{priority_class=~\"cluster-monitoring\",cluster=\"$cluster\",namespace!~\"kube-system|monitoring|fluentd\"}) OR on() vector(0)",
     "legendFormat": "cluster-monitoring"
    },
    {
     "expr": "count(kube_pod_info{priority_class=~\"selfservice\",cluster=\"$cluster\",namespace!~\"selfservice|selfservice-herald-vbqkr|developerautomation-xavgy\"}) OR on() vector(0)",
     "legendFormat": "selfservice"
    }
   ]
  }
 ]
}