{
 "title": "Cluster Health",
 "tags": [
  "AWS",
  "EKS",
  "Kubernetes"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API server 5xx errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (code_resource:apiserver_request_total:rate5m{code=~\"5..\",cluster=\"$cluster\"})",
     "legendFormat": "Abs {{code}}"
    },
    {
     "expr": "(sum by (code) (code_resource:apiserver_request_total:rate5m{code=~\"5..\",cluster=\"$cluster\"}) / sum by (code) (code_resource:apiserver_request_total:rate5m)) * 100",
     "legendFormat": "Rel {{code}}"
    }
   ]
  },
  {
   "title": "Liveness probe fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prober_probe_total{cluster=\"$cluster\",result=\"failed\", probe_type=\"Liveness\"}[15m])) by(node)*60*15",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Readiness probe fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prober_probe_total{cluster=\"$cluster\",result=\"failed\", probe_type=\"Readiness\"}[15m])) by(node)*60*15",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}