{
 "title": "Cluster Capacity",
 "tags": [
  "AWS",
  "EKS",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Pod Capacity",
   "type": "timeseries",
   "description": "The number of pods the cluster can provision.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", resource=\"pods\"})",
     "legendFormat": "Pod Capacity"
    }
   ]
  },
  {
   "title": "Pod Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"}) / sum(kube_node_status_capacity{resource=\"pods\",cluster=\"$cluster\"})",
     "legendFormat": "Pod Capacity Utilization"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"$cluster\"})",
     "legendFormat": "CPU Capacity"
    }
   ]
  },
  {
   "title": "CPU Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"$cluster\"})",
     "legendFormat": "CPU Capacity Utilization"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"$cluster\"})",
     "legendFormat": "Memory Capacity"
    }
   ]
  },
  {
   "title": "Memory Capacity Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"$cluster\"})",
     "legendFormat": "Memory Capacity Utilization"
    }
   ]
  }
 ]
}