{
 "title": "EC2 Credits",
 "description": "This chart shows CPU Credit balance and usage for our Kubernetes Cluster EC2 instances.",
 "tags": [
  "AWS",
  "EC2"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Credit Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Surplus Credit Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUSurplusCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Credit Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "60",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Credit Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}