{
 "title": "EKS version",
 "tags": [
  "AWS",
  "EKS",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Current cluster version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(eks_version_exporter{cluster=\"$cluster\"}) by (server_current_version)",
     "legendFormat": "{{server_current_version}}"
    }
   ]
  },
  {
   "title": "Latest available Kubernetes release",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(eks_version_exporter{cluster=\"$cluster\"}) by (k8s_latest_available_version)",
     "legendFormat": "{{k8s_latest_available_version}}"
    }
   ]
  },
  {
   "title": "Latest available EKS release",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(eks_version_exporter{cluster=\"$cluster\"}) by (eks_latest_available_version)",
     "legendFormat": "{{eks_latest_available_version}}"
    }
   ]
  },
  {
   "title": "Oldest supported EOL Kubernetes version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(eks_version_exporter{cluster=\"$cluster\"}) by (eol_latest_available_version)",
     "legendFormat": "{{eol_latest_available_version}}"
    }
   ]
  },
  {
   "title": "Last updated (UTC)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(eks_version_exporter{cluster=\"$cluster\"}) by (last_updated_text)",
     "legendFormat": "{{last_updated_text}}"
    }
   ]
  },
  {
   "title": "Is cluster version outdated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eks_version_exporter_is_outdated{cluster=\"$cluster\"}",
     "legendFormat": "is_outdated"
    }
   ]
  },
  {
   "title": "Is cluster version past EOL",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eks_version_exporter_is_past_eol{cluster=\"$cluster\"}",
     "legendFormat": "is_outdated"
    }
   ]
  }
 ]
}