{
 "title": "Kafka-exporter",
 "description": "A dashboard for monitoring kafka-exporter",
 "tags": [
  "Exporter",
  "Kafka",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "k8s_cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "kafka_cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Topic consumergroups",
   "type": "timeseries",
   "description": "Amount of consumergroups per topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kafka_consumergroup_lag{cluster=\"$kafka_cluster\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "topics with more than 10 consumer groups",
   "type": "timeseries",
   "description": "Amount of consumergroups per topic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (consumergroup, topic) (kafka_consumergroup_lag{cluster=\"$kafka_cluster\"})) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka-exporter up",
   "type": "timeseries",
   "description": "Can Prometheus scrape metrics from kafka-exporter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{cluster=\"$k8s_cluster\", job=\"kafka-exporter-lkc-4npj6\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}