{
 "title": "Kubernetes Components",
 "tags": [
  "AWS",
  "EKS",
  "Kubernetes",
  "AddOns"
 ],
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Kubelet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (kubelet_version) (kube_node_info{cluster=\"$cluster\"})",
     "legendFormat": "{{kubelet_version}}"
    }
   ]
  },
  {
   "title": "Kube-Proxy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (image) (kube_pod_container_info{namespace=\"kube-system\", container=\"kube-proxy\",cluster=\"$cluster\"})",
     "legendFormat": "{{image}}"
    },
    {
     "expr": "sum by (daemonset) (kube_daemonset_status_desired_number_scheduled{namespace=\"kube-system\", daemonset=\"kube-proxy\",cluster=\"$cluster\"}) - sum by (daemonset) (kube_daemonset_status_number_available{namespace=\"kube-system\", daemonset=\"kube-proxy\",cluster=\"$cluster\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "CoreDNS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (image) (kube_pod_container_info{namespace=\"kube-system\", container=\"coredns\",cluster=\"$cluster\"})",
     "legendFormat": "{{image}}"
    },
    {
     "expr": "sum by (deployment) (kube_deployment_spec_replicas{namespace=\"kube-system\", deployment=\"coredns\",cluster=\"$cluster\"}) - sum by (deployment) (kube_deployment_status_replicas_available{namespace=\"kube-system\", deployment=\"coredns\",cluster=\"$cluster\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "VPC CNI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (image) (kube_pod_container_info{namespace=\"kube-system\", container=\"aws-node\",cluster=\"$cluster\"})",
     "legendFormat": "{{image}}"
    },
    {
     "expr": "sum by (daemonset) (kube_daemonset_status_desired_number_scheduled{namespace=\"kube-system\", daemonset=\"aws-node\",cluster=\"$cluster\"}) - sum by (daemonset) (kube_daemonset_status_number_available{namespace=\"kube-system\", daemonset=\"aws-node\",cluster=\"$cluster\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Components version bump alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (image) (kube_pod_container_info{namespace=\"kube-system\", container=\"aws-node\",cluster=\"$cluster\"})) - 2",
     "legendFormat": "cni"
    },
    {
     "expr": "count(count by (image) (kube_pod_container_info{namespace=\"kube-system\", container=\"kube-proxy\",cluster=\"$cluster\"})) - 1",
     "legendFormat": "kube-proxy"
    },
    {
     "expr": "count(count by (image) (kube_pod_container_info{namespace=\"kube-system\", container=\"coredns\"})) - 1",
     "legendFormat": "coredns"
    },
    {
     "expr": "count(count by (kubelet_version) (kube_node_info{cluster=\"$cluster\"})) - 2",
     "legendFormat": "kubelet"
    }
   ]
  }
 ]
}