{
 "title": "readiness / liveness probes in namespace",
 "tags": [
  "Kubernetes",
  "Probes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(exported_namespace)"
    }
   },
   { "name": "datasources", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Containers - readiness probes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_readiness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})",
     "legendFormat": "Has probes"
    },
    {
     "expr": "count(k8s_readiness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"}) - sum(k8s_readiness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})",
     "legendFormat": "No probes"
    }
   ]
  },
  {
   "title": "Containers - liveness probes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_liveness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})",
     "legendFormat": "Has probes"
    },
    {
     "expr": "count(k8s_liveness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"}) - sum(k8s_liveness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})",
     "legendFormat": "No probes"
    }
   ]
  },
  {
   "title": "Deployments - readiness probes coverage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(k8s_readiness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})) / count(k8s_readiness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})",
     "legendFormat": "Has probes"
    }
   ]
  },
  {
   "title": "Deployments - liveness probes coverage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(k8s_liveness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})) / count(k8s_liveness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"})",
     "legendFormat": "Has probes"
    }
   ]
  },
  {
   "title": "Readiness by (deployment - container)",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "k8s_readiness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"}",
     "legendFormat": "{{deployment}} - {{exported_container}}"
    }
   ]
  },
  {
   "title": "Liveness by (deployment - container)",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "k8s_liveness_probe_exists{cluster=\"$cluster\",exported_namespace=\"[[namespace]]\"}",
     "legendFormat": "{{deployment}} - {{exported_container}}"
    }
   ]
  }
 ]
}