{
 "title": "Priority class",
 "description": "Monitoring distribution of priorityclasses",
 "tags": [
  "AWS",
  "EKS",
  "Kubernetes",
  "Classes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Priority class by namespaces",
   "type": "table",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"}) by (priority_class, namespace)"
    }
   ]
  },
  {
   "title": "Priority class distribution",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 13, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\"}) by (priority_class)",
     "legendFormat": "{{priority_class}}"
    }
   ]
  },
  {
   "title": "Alert graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\",priority_class=\"selfservice\", namespace!=\"selfservice\", namespace!=\"selfservice-herald-vbqkr\", namespace!=\"developerautomation-xavgy\", namespace!=\"velero\"}) by (pririty_class, namespace)",
     "legendFormat": "Selfservice priority class"
    },
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\",priority_class=\"service-critical\", namespace!=\"kube-system\"}) by (pririty_class, namespace)",
     "legendFormat": "Service critical priority class"
    },
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\",priority_class=\"cluster-monitoring\", namespace!=\"alcide\", namespace!=\"kube-system\", namespace!=\"kube-system\", namespace!=\"monitoring\", namespace!=\"grafana\"}) by (pririty_class, namespace)",
     "legendFormat": "Cluster monitoring priority class"
    },
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\",priority_class=\"system-node-critical\", namespace!=\"kube-system\"}) by (pririty_class, namespace)",
     "legendFormat": "System node critical priority class"
    }
   ]
  }
 ]
}