{
 "title": "Prometheus Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "AWS",
  "EKS",
  "Kubernetes",
  "Synthetic",
  "Traefik",
  "Atlantis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   },
   { "name": "datasources", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Probe status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "probe_success{cluster=\"$cluster\"}",
     "legendFormat": "{{  instance }}"
    }
   ]
  },
  {
   "title": "SSL expiry overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=\"$cluster\"} - time()",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{cluster=\"$cluster\",instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=\"$cluster\",instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{cluster=\"$cluster\",instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{cluster=\"$cluster\",instance=~\"$target\"})"
    }
   ]
  }
 ]
}