{
 "title": "Selfservice -- Tagging Adoption",
 "tags": [
  "selfservice",
  "adoption"
 ],
 "time": { "from": "2024-05-29T09:26:02.189Z", "to": "2024-05-29T10:26:51.151Z" },
 "templating": {
  "list": [
   {
    "name": "tribe",
    "label": "tribe",
    "query": {
     "query": "label_values(selfservice_capability{namespace=\"selfservice\"},cost_centre)"
    }
   },
   {
    "name": "tribe_account_ids",
    "label": "AWS Account Ids for tribe",
    "query": {
     "query": "label_values(selfservice_capability{cost_centre=\"$tribe\"},aws_acccount_id)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(aws_resource,dfds_env)"
    }
   },
   {
    "name": "resource_type",
    "label": "Resource Type",
    "query": {
     "query": "label_values(aws_resource,type)"
    }
   },
   {
    "name": "tag",
    "label": "Tag",
    "query": "dfds_env, dfds_data_backup, dfds_data_classification, dfds_service_criticality, dfds_service_availability"
   }
  ]
 },
 "panels": [
  { "title": "DFDS Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DFDS total $resource_type instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_resource{type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS tagged $resource_type instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_resource{type=~\"^($resource_type)$\", $tag!=\"\", dfds_env=~\"${environment:pipe}$\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS $resource_type $tag compliance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ((sum(aws_resource{type=~\"^($resource_type)$\", $tag!=\"\",  dfds_env=~\"${environment:pipe}$\"}) / sum(aws_resource{type=~\"^($resource_type)$\",  dfds_env=~\"${environment:pipe}$\"})) * 100) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS total $resource_type instances (with no_env)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_resource{type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}|\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS tagged $resource_type instances (with no env)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_resource{type=~\"^($resource_type)$\", $tag!=\"\", dfds_env=~\"${environment:pipe}|\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS $resource_type $tag compliance (with no_env)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ((sum(aws_resource{type=~\"^($resource_type)$\", $tag!=\"\",  dfds_env=~\"${environment:pipe}|$\"}) / sum(aws_resource{type=~\"^($resource_type)$\",  dfds_env=~\"${environment:pipe}|$\"})) * 100) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tribal: $tribe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$tribe total $resource_type instances",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}\"}) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$tribe tagged $resource_type instances",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", $tag!=\"\", dfds_env=~\"${environment:pipe}\"}) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$tribe $resource_type $tag compliance",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}\", $tag!=\"\"}) / sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}\"})) * 100) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$tribe total $resource_type instances (with no_env)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}|\"}) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$tribe tagged $resource_type instances (with no_env)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", $tag!=\"\", dfds_env=~\"${environment:pipe}|\"}) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$tribe $resource_type $tag compliance (with no_env)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}|\", $tag!=\"\"}) / sum(aws_resource{AccountId=~\"^($tribe_account_ids)$\", type=~\"^($resource_type)$\", dfds_env=~\"${environment:pipe}|\"})) * 100) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Static", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "DFDS Environments for selected resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(dfds_env) (aws_resource{type=~\"${resource_type:pipe}\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "DFDS cost centre for all environments and all resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(dfds_cost_centre) (aws_resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS rds_db backup tags (prod and no_env)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(dfds_data_backup) (aws_resource{type=\"rds:db\", dfds_env=~\"prod|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS security tags for all environments and all resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(dfds_data_classification) (aws_resource)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(dfds_service_criticality) (aws_resource)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(dfds_service_availability) (aws_resource)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}