{
 "title": "SelfService -- RDS Tagging Compliance",
 "tags": [
  "selfservice",
  "adoption"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tribe",
    "label": "tribe",
    "query": {
     "query": "label_values(selfservice_capability{namespace=\"selfservice\"},cost_centre)"
    }
   },
   {
    "name": "capability_id",
    "label": "Capability",
    "query": {
     "query": "label_values(selfservice_capability{cost_centre=\"$tribe\", namespace=\"selfservice\"},id)"
    }
   },
   {
    "name": "tribe_account_ids",
    "label": "AWS Account Ids for tribe",
    "query": {
     "query": "label_values(selfservice_capability{cost_centre=\"$tribe\"},aws_acccount_id)"
    }
   },
   { "name": "tag", "label": "Tag", "query": "dfds_env, dfds_data_backup" }
  ]
 },
 "panels": [
  { "title": "T&I All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DFDS Total RDS Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_rds_db{}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS RDS Instances with Backup Tag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_rds_db{$tag!=\"\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFDS Backup Tag Compliance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(aws_rds_db{$tag!=\"\"}) / sum(aws_rds_db{})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compliance Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(aws_rds_db{$tag!=\"\"}) / sum(aws_rds_db)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$tribe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total RDS databases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_rds_db{AccountId=~\"^($tribe_account_ids)$\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tagged Databases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_rds_db{AccountId=~\"^($tribe_account_ids)$\", $tag!=\"\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tagging Compliance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(aws_rds_db{AccountId=~\"^($tribe_account_ids)$\", $tag!=\"\"}) / sum(aws_rds_db{AccountId=~\"^($tribe_account_ids)$\"}) * 100) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compliance Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(aws_rds_db{AccountId=~\"^($tribe_account_ids)$\", $tag!=\"\"}) / sum(aws_rds_db{AccountId=~\"^($tribe_account_ids)$\"}) * 100) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capability $capability_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDS Instances",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aws_rds_db * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\")) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RDS Instances with Backup Tag",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (sum(aws_rds_db{dfds_data_backup=\"true\"} * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\"))) + (sum(aws_rds_db{dfds_data_backup=\"false\"} * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\"))) OR on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backup Tag Compliance",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((sum (sum(aws_rds_db{dfds_data_backup=\"true\"} * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\"))) + (sum(aws_rds_db{dfds_data_backup=\"false\"}  * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\")))) / sum(aws_rds_db * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\")) OR on() vector(0)) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compliance Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((sum (sum(aws_rds_db{dfds_data_backup=\"true\"} * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\"))) + (sum(aws_rds_db{dfds_data_backup=\"false\"}  * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\")))) / sum(aws_rds_db * on (AccountId) group_left(id) label_replace(selfservice_capability{id=\"$capability_id\", namespace=\"selfservice\"}, \"AccountId\", \"$1\", \"aws_acccount_id\", \"(.*)\")) OR on() vector(0)) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}