{
 "title": "aad-aws-sync",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Is job running",
   "type": "stat",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(sum(aad_aws_sync_job_is_running) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successful job count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(aad_aws_sync_job_success_count[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failed job count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(aad_aws_sync_job_failed_count[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current jobs running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(aad_aws_sync_jobs_running)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Email aliases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aad_aws_sync_exchange_email_aliases_count"
    }
   ]
  },
  {
   "title": "Missing email aliases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aad_aws_sync_exchange_email_missing_aliases_count"
    }
   ]
  },
  {
   "title": "email alias mismatch (aliases - caps)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aad_aws_sync_exchange_email_alias_capabilities_mismatch"
    }
   ]
  }
 ]
}