{
 "title": "aws-sso-exporter",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "<span style=\"font-size: 3em\">Authenticate</span>"
   }
  },
  {
   "title": "Unique users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_unique_users) by (name)",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_unique_users)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total sign-ins",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_total_signins) by (name)",
     "legendFormat": "sign-ins"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_total_signins)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average sign-ins",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_average_user_signin) by (name)",
     "legendFormat": "sign-ins"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_average_user_signin)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mean sign-ins",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_mean_user_signin) by (name)",
     "legendFormat": "sign-ins"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_authenticate_mean_user_signin)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}