{
 "title": "Selfservice",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Apps running",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{namespace=~\"selfservice.*\", service=~\"confluent-gateway|selfservice-api|k8s-janitor\"}) by (service) - sum(up{namespace=~\"selfservice.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{namespace=~\"selfservice.*\", service=~\"selfservice-api\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Apps not running timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{namespace=~\"selfservice.*\"}) by (service) - sum(up{namespace=~\"selfservice.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Failed request rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\",backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}} 5XX"
    },
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"4..\",backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}} 4XX"
    },
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5..\", namespace=~\"selfservice.*\", service=~\"selfservice-api\"}[5m])) by (service)",
     "legendFormat": "{{service}} 5XX"
    },
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"4..\", namespace=~\"selfservice.*\", service=~\"selfservice-api\"}[5m])) by (service)",
     "legendFormat": "{{service}} 4XX"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{backend=~\"build.dfds.cloud\"}[5m])) by (backend) / sum(rate(traefik_backend_request_duration_seconds_count{backend=~\"build.dfds.cloud\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=~\"selfservice.*\",service=~\"selfservice-api\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "timeseries",
   "description": "Consumer group lag of build.capabilities kafka topic",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"cloudengineering.*\",consumergroup!=\"\",consumergroup!=\"iam-role-service-consumer\",consumergroup!=\"argojanitor-consumer-production\",consumergroup!~\"developerautomation-xavgy.*\",consumergroup!=\"build.selfservice.aadawssync\",consumergroup!=\"cloudengineering.ssu-mgmt\"}) by (topic,consumergroup)",
     "legendFormat": "{{topic}}:{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Messages in per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=~\"cloudengineering.*\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}