{
 "title": "aws-sso-exporter - Web sign-ins",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "<span style=\"font-size: 3em\">Web sign-ins (federate)</span>"
   }
  },
  {
   "title": "Unique users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_unique_users) by (name)",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_unique_users)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total roles assumed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_roles_assumed) by (name)",
     "legendFormat": "sign-ins"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_roles_assumed)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average roles assumed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_average_roles_assumed) by (name)",
     "legendFormat": "sign-ins"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_average_roles_assumed)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mean roles assumed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_mean_roles_assumed) by (name)",
     "legendFormat": "sign-ins"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aws_sso_exporter_federate_mean_roles_assumed)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}