{
 "title": "Platform Data API",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Aws Resources Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(platform_data_api_awsResourceCount_request_count_cached[5m])/rate(platform_data_api_awsResourceCount_request_count[5m])",
     "legendFormat": "cached"
    },
    {
     "expr": "rate(platform_data_api_awsResourceCount_request_count_failed[5m])/rate(platform_data_api_awsResourceCount_request_count[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "rate(platform_data_api_awsResourceCount_request_count_non_cached[5m])/rate(platform_data_api_awsResourceCount_request_count[5m])",
     "legendFormat": "non-cached"
    }
   ]
  },
  {
   "title": "Aws Resource Count Athena Query Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(platform_data_api_awsResourceCount_athena_query_duration_sum[5m]) / rate(platform_data_api_awsResourceCount_athena_query_duration_count[5m])",
     "legendFormat": "query duration"
    }
   ]
  },
  {
   "title": "Finout Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(platform_data_api_finout_request_count_cached[5m])/rate(platform_data_api_finout_request_count[5m])",
     "legendFormat": "cached"
    },
    {
     "expr": "rate(platform_data_api_finout_request_count_failed[5m])/rate(platform_data_api_finout_request_count[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "rate(platform_data_api_finout_request_count_non_cached[5m])/rate(platform_data_api_finout_request_count[5m])",
     "legendFormat": "non-cached"
    }
   ]
  },
  {
   "title": "Finout Athena Query Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(platform_data_api_finout_athena_query_duration_sum[5m]) / rate(platform_data_api_finout_athena_query_duration_count[5m])",
     "legendFormat": "query duration"
    }
   ]
  },
  {
   "title": "Number of Shared Caches in Use",
   "type": "timeseries",
   "description": "Platform Data API uses a caching system in order to not use athena with every data request",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "platform_data_api_in_memory_cache_count"
    }
   ]
  }
 ]
}