{
 "title": "data-collector-finout",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Is job running",
   "type": "stat",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(sum(data_collector_finout_job_is_running) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successful job count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(data_collector_finout_job_success_count[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failed job count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(data_collector_finout_job_failed_count[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current jobs running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(data_collector_finout_jobs_running)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}