{
 "title": "Traefik - Blue/Green Deployment",
 "tags": [
  "Controller",
  "Ingress",
  "Kubernetes",
  "Traefik"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Entrypoint requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{cluster=\"$cluster\",namespace=\"traefik-blue-variant\"}[5m]))",
     "legendFormat": "Blue"
    },
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{cluster=\"$cluster\",namespace=\"traefik-green-variant\"}[5m]))",
     "legendFormat": "Green"
    }
   ]
  },
  {
   "title": "Service requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{cluster=\"$cluster\",namespace=\"traefik-blue-variant\"}[5m]))",
     "legendFormat": "Blue"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{cluster=\"$cluster\",namespace=\"traefik-green-variant\"}[5m]))",
     "legendFormat": "Green"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "5XX error rate",
   "type": "stat",
   "description": "Rate of 5XX errors amongst all entry point requests.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{cluster=\"$cluster\",entrypoint=\"web\",namespace=\"traefik-blue-variant\", code=~\"[5][0-9]{2}\"}[5m]))*100/sum(rate(traefik_entrypoint_requests_total{cluster=\"$cluster\",entrypoint=\"web\",namespace=\"traefik-blue-variant\"}[5m]))",
     "legendFormat": "Blue"
    },
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{cluster=\"$cluster\",entrypoint=\"web\",namespace=\"traefik-green-variant\", code=~\"[5][0-9]{2}\"}[5m]))*100/sum(rate(traefik_entrypoint_requests_total{cluster=\"$cluster\",entrypoint=\"web\",namespace=\"traefik-green-variant\"}[5m]))",
     "legendFormat": "Green"
    }
   ]
  }
 ]
}