{
 "title": "Traefik Migration V3",
 "description": "Monitor Traefik v3 Upgrade",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traefik Ingressroute resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_traefik{customresource_kind=\"IngressRoute\"}) by (customresource_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik Middleware resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_traefik{customresource_kind=\"Middleware\"}) by (customresource_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik IngressRoute resources with old API",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_customresource_traefik{customresource_kind=\"IngressRoute\", customresource_group=\"traefik.containo.us\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik Middleware with old API",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_customresource_traefik{customresource_kind=\"Middleware\", customresource_group=\"traefik.containo.us\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}