name: Grafana Cloud resources

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - .gitignore
      - LICENSE
      - "*.md"
      - renovate.json
      - atlantis.yaml

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT from OIDC provider
  contents: read # This is required for actions/checkout

concurrency: terragrunt

defaults:
  run:
    shell: bash

env:
  TF_IN_AUTOMATION: "true"
  TERRAGRUNT_TFPATH: /usr/local/bin/tofu

jobs:
  deploy-to-grafana-cloud:
    strategy:
      matrix:
        environment:
          - platform
        include:
          - environment: platform
            slack_alert_webhook: GRAFANA_CLOUD_SLACK_WEBHOOK
    runs-on: ubuntu-latest
    container:
      image: dfdsdk/prime-pipeline:2.1.0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CORE_ROLE_TO_ASSUME }}
          role-session-name: provision-grafana-objects
          aws-region: eu-central-1

      - name: Deploy resources to Grafana Cloud ${{ matrix.environment }} environment
        env:
          TF_VAR_synthetic_basic_auth: '{"atlantis_auth": {"username": "${{ secrets.PROD_ATLANTIS_USERNAME }}", "password": "${{ secrets.PROD_ATLANTIS_PASSWORD }}" }}'
          TF_VAR_notification_slack_webhook_url: ${{ secrets[matrix.slack_alert_webhook] }}
          TF_VAR_infinity_bearer_token: ${{ secrets.GRAFANA_CLOUD_INFINITY_DATASOURCE_GITHUB }}
        run: terragrunt run-all apply --terragrunt-working-dir ./environments/${{ matrix.environment }} --terragrunt-source-update --terragrunt-non-interactive -input=false -auto-approve

      - name: Send alert if job fails
        if: failure()
        uses: dfds/shared-workflows/.github/actions/automation-slack-notifier@master
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_message: "Configure Grafana Cloud environment failed."
