name: Grafana Cloud resources

on:
  push:
    branches: [main]
    paths-ignore:
      - .github/**
      - .gitignore
      - LICENSE
      - README.md
      - renovate.json

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT from OIDC provider
  contents: read # This is required for actions/checkout

concurrency: terragrunt

defaults:
  run:
    shell: bash

jobs:
  deploy-to-grafana-cloud:
    runs-on: ubuntu-latest
    container:
      image: dfdsdk/prime-pipeline:0.6.37
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CORE_ROLE_TO_ASSUME }}
          role-session-name: provision-grafana-objects
          aws-region: eu-central-1

      - name: Deploy resources to Grafana Cloud sandbox environment
        env:
          TF_VAR_grafana_url: ${{ secrets.GRAFANA_CLOUD_URL_FOR_SANDBOX }}
          TF_VAR_grafana_auth: ${{ secrets.GRAFANA_CLOUD_SERVICE_ACCOUNT_TOKEN_FOR_SANDBOX }}
        run: terragrunt run-all apply --terragrunt-working-dir ./environments/sandbox --terragrunt-source-update --terragrunt-non-interactive -input=false -auto-approve

      - name: Deploy resources to Grafana Cloud demo environment
        env:
          TF_VAR_grafana_url: ${{ secrets.GRAFANA_CLOUD_URL_FOR_DEMO }}
          TF_VAR_grafana_auth: ${{ secrets.GRAFANA_CLOUD_SERVICE_ACCOUNT_TOKEN_FOR_DEMO }}
        run: terragrunt run-all apply --terragrunt-working-dir ./environments/demo --terragrunt-source-update --terragrunt-non-interactive -input=false -auto-approve

      - name: Send alert if job fails
        if: failure()
        uses: dfds/shared-workflows/.github/actions/automation-slack-notifier@master
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_message: "Configure Grafana Cloud environment failed."
